### ISSUE TITLE
Increase in range != increase in emissions

### ISSUE THREAD

**Issue by hoser21** [upcs/cs341-project-ss2020-python#20]
When the range is increased on the graph-info page, the emissions rate sometimes goes down. This doesn't make sense since a bigger range should encompass the same amount of plants or more, so the emission rate should either stay the same or increase.

**Comment by argiesemann** [comment]
Ahh yes, well it's getting the average value. So sometimes increasing the range gets you more data points that are lower than the previous average

**Comment by hoser21** [comment]
Ah, this make sense.
