### ISSUE TITLE
Second City Stays in graph after unchecking "Check for second city"

### ISSUE THREAD

**Issue by marcial21** [upcs/cs341-project-ss2020-python#56]
Steps to recreate:
1. Navigate to Plant Graphs
2. Type in two cities. 
3. Select at least one plant type.
4. Choose one or two metrics
5. Have X-axis be either plant or city. 
6. Click Create Graph
7. Uncheck the "Check for second city" check box. 
8. Click on Create Graph again. 

The contents from the second city still remain on the graph when its created.

**Comment by hoser21** [comment]
This is fixed in the latest update
