### ISSUE TITLE
Cities

### ISSUE THREAD

**Issue by dendinge21** [upcs/cs341-project-ss2020-python#66]
How do you know which cities you can choose from. Is it just major cities in each state?

**Comment by marcial21** [comment]
American cities.

**Comment by dendinge21** [comment]
Do some just not have data associated with them? If some do not have a plant in the city, some message should pop up and say there is no ____ plant in this city so the user knows whats going on perhaps

**Comment by hojo21** [comment]
No all American cities work and have data associated with it.

**Comment by hoser21** [comment]
Listing all US cities that we have data for is too much, so we added a feature that will show a pop-up alert when a search query has no results.
