### ISSUE TITLE
Search Panel is unintuitive

### ISSUE THREAD

**Issue by liao21** [upcs/cs341-project-ss2020-python#71]
When you go to search for something and click on the search bar, the panel pops up. However, if your mouse is already there, the panel does not pop up. I think it should. 

Also, more egregiously, when you click anywhere else on the website (except the search bar) the search bar doesn't go away. I think it should because it is not intuitive that you have to click on the search bar again to make the search panel go away. 

Try .onMouseEnter(). for the rest of the page, or maybe .onMouseExit() which I have not used.

**Comment by morana21** [comment]
duplicate with #64
