### ISSUE TITLE
Graph SQL injection

### ISSUE THREAD

**Issue by regier21** [upcs/cs341-project-ss2020-python#72]
Setting the city to Portland OR 1=1 will fetch data for all cities in database.

**Comment by hoser21** [comment]
I can't recreate this. Can you give a screenshot of your settings?

**Comment by pirkl21** [comment]
Set City 1 to : Portland OR 1=1
then set the other settings to whatever you want and click create graph.
After you click create graph, if you click f12 (devtools) and browse to the Network tab, you should be able to see a GET request. click on it and then go to the response tab.

**Comment by hoser21** [comment]
Interesting. Luckily, this isn't our data and is from the OpenStreetMaps API. We may look into preventing this.

**Comment by hojo21** [comment]
We have decided not to implement this feature.
