### ISSUE TITLE
Energy Info, World Energy Explained Inconsistancy 

### ISSUE THREAD

**Issue by liao21** [upcs/cs341-project-ss2020-python#74]
The Energy Info tab takes you to the World Energy Explained page. I don't think that's intuitive. 

Also, on that page, each of the images 
a) the images look clickable 
b) the images are all ***slightly*** different sizes. It might work if they were more different, but it's just frustrating to look at right now.

**Comment by hojo21** [comment]
We do not plan to make the images look less clickable.
