### ISSUE TITLE
No Error Checking for Cities

### ISSUE THREAD

**Issue by bunger20** [upcs/cs341-project-ss2020-python#76]
You can add a fake city to the graph and the site does not attempt to check for this error.
<img width="969" alt="Screen Shot 2020-04-02 at 11 06 01 AM" src="https://user-images.githubusercontent.com/45083922/78283275-66827000-74d2-11ea-95ed-32fcd22e640f.png">

**Comment by morana21** [comment]
giving a city that doesn't exist gives passes and empty graph for that city

**Comment by hoser21** [comment]
This is now fixed in the latest version.
